### ISSUE TITLE
Create a new function that returns something

### ISSUE THREAD

**Issue by soinegve** [papakos21/project1#3]
The function dekada is good but it doesn't return anything . It only prints
Functions that do not return results are more difficult to test and testing is very important

Create a new function ( keep old ) in the functions.py file maybe name 
get_dekada() that instead of printing it returns an array from 1 to 10

```
def get_dekada():
     
     result = []
     #build result by making a one line modification of previous code ( remove print line and add something else ) 
     for x in range(1,11):
            print(x)  # remove this and add result.append(x)
    
     return result
```

then in main you can run print(get_dekada()) and see what happens

result is a list read about list here 
https://sites.google.com/site/usfcomputerscience/Lists

**Comment by papakos21** [comment]
IS IT CLOSED YET?

**Comment by soinegve** [comment]
Yes
